"""
v4 · P4 Identity & onboarding (spec §11, §12, §14, §15) + support tickets (§19.8)

Columns on admin_users: account status, token_version, phone verification,
rating_count, marketing consent, admin roles, locale.
Tables: phone_verifications, user_devices, legal_documents, legal_acceptances,
driver_applications, driver_documents, background_checks, support_tickets,
support_ticket_messages.
"""
from backend.database.schema_helpers import (
    add_columns, add_index, create_tables, drop_columns, drop_tables, TABLE_OPTS)

USER_COLUMNS = [
    "account_status VARCHAR(20) NULL DEFAULT NULL",
    "status_reason VARCHAR(500) NULL DEFAULT NULL",
    "status_reason_code VARCHAR(40) NULL DEFAULT NULL",
    "status_changed_by INT NULL DEFAULT NULL",
    "status_changed_at DATETIME NULL DEFAULT NULL",
    "suspended_until DATETIME NULL DEFAULT NULL",
    "pending_account_status VARCHAR(20) NULL DEFAULT NULL",
    "token_version INT NOT NULL DEFAULT 0",
    "phone_e164 VARCHAR(20) NULL DEFAULT NULL",
    "phone_verified_at DATETIME NULL DEFAULT NULL",
    "phone_line_type VARCHAR(30) NULL DEFAULT NULL",
    "rating_count INT NOT NULL DEFAULT 0",
    "rating_avg_raw DECIMAL(4,3) NULL DEFAULT NULL",
    "marketing_opt_in TINYINT(1) NOT NULL DEFAULT 0",
    "marketing_opt_in_at DATETIME NULL DEFAULT NULL",
    "admin_roles VARCHAR(255) NULL DEFAULT NULL",
    "preferred_language VARCHAR(5) NULL DEFAULT NULL",
    "timezone VARCHAR(60) NULL DEFAULT NULL",
    "province VARCHAR(2) NULL DEFAULT NULL",
    "legal_name VARCHAR(200) NULL DEFAULT NULL",
]

TABLES = [
    f"""CREATE TABLE phone_verifications (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NULL,
        phone VARCHAR(20) NOT NULL,
        purpose VARCHAR(30) NOT NULL,
        channel VARCHAR(20) NOT NULL DEFAULT 'sms',
        twilio_sid VARCHAR(64) NULL,
        status VARCHAR(20) NOT NULL DEFAULT 'pending',
        attempts INT NOT NULL DEFAULT 0,
        ip VARCHAR(64) NULL,
        device_id VARCHAR(191) NULL,
        token_hash CHAR(64) NULL,
        token_expires_at DATETIME NULL,
        consumed_at DATETIME NULL,
        test_mode TINYINT(1) NOT NULL DEFAULT 0,
        error VARCHAR(500) NULL,
        created_at DATETIME NOT NULL,
        verified_at DATETIME NULL,
        KEY ix_pv_phone (phone, created_at),
        KEY ix_pv_ip (ip, created_at),
        KEY ix_pv_token (token_hash)
    ) {TABLE_OPTS}""",
    f"""CREATE TABLE user_devices (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        device_id VARCHAR(191) NOT NULL,
        platform VARCHAR(20) NULL,
        label VARCHAR(191) NULL,
        trusted_at DATETIME NULL,
        first_seen_at DATETIME NOT NULL,
        last_seen_at DATETIME NULL,
        last_ip VARCHAR(64) NULL,
        UNIQUE KEY uq_user_device (user_id, device_id)
    ) {TABLE_OPTS}""",
    f"""CREATE TABLE legal_documents (
        id INT AUTO_INCREMENT PRIMARY KEY,
        type VARCHAR(40) NOT NULL,
        version VARCHAR(20) NOT NULL,
        title VARCHAR(200) NOT NULL,
        summary_markdown TEXT NULL,
        what_changed TEXT NULL,
        body_markdown LONGTEXT NOT NULL,
        language VARCHAR(5) NOT NULL DEFAULT 'en',
        audience VARCHAR(20) NOT NULL DEFAULT 'all',
        status VARCHAR(20) NOT NULL DEFAULT 'draft',
        requires_reacceptance TINYINT(1) NOT NULL DEFAULT 0,
        effective_at DATETIME NULL,
        published_at DATETIME NULL,
        published_by INT NULL,
        created_at DATETIME NOT NULL,
        updated_at DATETIME NULL,
        UNIQUE KEY uq_legal_version (type, version, language),
        KEY ix_legal_type_status (type, status)
    ) {TABLE_OPTS}""",
    f"""CREATE TABLE legal_acceptances (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        document_id INT NOT NULL,
        document_type VARCHAR(40) NOT NULL,
        version VARCHAR(20) NOT NULL,
        accepted_at DATETIME NOT NULL,
        ip VARCHAR(64) NULL,
        user_agent VARCHAR(500) NULL,
        app_version VARCHAR(30) NULL,
        method VARCHAR(20) NOT NULL DEFAULT 'checkbox',
        signature_name VARCHAR(200) NULL,
        UNIQUE KEY uq_accept (user_id, document_id),
        KEY ix_accept_doc (document_id)
    ) {TABLE_OPTS}""",
    f"""CREATE TABLE driver_applications (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        status VARCHAR(30) NOT NULL DEFAULT 'in_progress',
        current_step VARCHAR(40) NOT NULL DEFAULT 'account_created',
        steps JSON NULL,
        legal_first_name VARCHAR(100) NULL,
        legal_last_name VARCHAR(100) NULL,
        date_of_birth DATE NULL,
        address_line VARCHAR(255) NULL,
        city VARCHAR(100) NULL,
        province CHAR(2) NULL,
        postal_code VARCHAR(10) NULL,
        service_types JSON NULL,
        licence_class VARCHAR(10) NULL,
        licence_number VARCHAR(60) NULL,
        licence_expires_at DATE NULL,
        vehicle_make VARCHAR(60) NULL,
        vehicle_model VARCHAR(60) NULL,
        vehicle_year INT NULL,
        vehicle_color VARCHAR(40) NULL,
        vehicle_plate VARCHAR(20) NULL,
        vehicle_seats INT NULL,
        prequal JSON NULL,
        orientation_completed_at DATETIME NULL,
        orientation_score INT NULL,
        pay_later_from_earnings TINYINT(1) NOT NULL DEFAULT 0,
        referral_code VARCHAR(20) NULL,
        referred_by INT NULL,
        submitted_at DATETIME NULL,
        reviewed_by INT NULL,
        reviewed_at DATETIME NULL,
        rejection_reason TEXT NULL,
        notes TEXT NULL,
        created_at DATETIME NOT NULL,
        updated_at DATETIME NULL,
        UNIQUE KEY uq_app_user (user_id),
        UNIQUE KEY uq_app_referral (referral_code),
        KEY ix_app_status (status)
    ) {TABLE_OPTS}""",
    f"""CREATE TABLE driver_documents (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        application_id BIGINT NOT NULL,
        user_id INT NOT NULL,
        type VARCHAR(40) NOT NULL,
        file_path VARCHAR(500) NOT NULL,
        mime_type VARCHAR(60) NULL,
        sha256 CHAR(64) NULL,
        expires_at DATE NULL,
        status VARCHAR(20) NOT NULL DEFAULT 'pending',
        reviewer_note VARCHAR(500) NULL,
        reviewed_by INT NULL,
        reviewed_at DATETIME NULL,
        reminders_sent JSON NULL,
        created_at DATETIME NOT NULL,
        updated_at DATETIME NULL,
        KEY ix_docs_app (application_id, type),
        KEY ix_docs_expiry (expires_at, status)
    ) {TABLE_OPTS}""",
    f"""CREATE TABLE background_checks (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        application_id BIGINT NULL,
        provider VARCHAR(20) NOT NULL DEFAULT 'certn',
        provider_application_id VARCHAR(191) NULL,
        package VARCHAR(80) NULL,
        status VARCHAR(30) NOT NULL DEFAULT 'awaiting_payment',
        result VARCHAR(30) NULL,
        report_url TEXT NULL,
        invite_url TEXT NULL,
        fee_cents BIGINT NOT NULL DEFAULT 0,
        fee_payment_id BIGINT NULL,
        fee_paid_at DATETIME NULL,
        paid_by VARCHAR(20) NOT NULL DEFAULT 'driver',
        consent_acceptance_id BIGINT NULL,
        adjudicated_by INT NULL,
        adjudicated_at DATETIME NULL,
        adjudication_note TEXT NULL,
        raw_status VARCHAR(60) NULL,
        initiated_at DATETIME NULL,
        completed_at DATETIME NULL,
        expires_at DATETIME NULL,
        last_polled_at DATETIME NULL,
        created_at DATETIME NOT NULL,
        updated_at DATETIME NULL,
        UNIQUE KEY uq_bgc_provider_app (provider, provider_application_id),
        KEY ix_bgc_user (user_id),
        KEY ix_bgc_status (status)
    ) {TABLE_OPTS}""",
    f"""CREATE TABLE support_tickets (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        type VARCHAR(30) NOT NULL DEFAULT 'general',
        ride_type VARCHAR(30) NULL,
        ride_id BIGINT NULL,
        subject VARCHAR(200) NOT NULL,
        body TEXT NULL,
        status VARCHAR(20) NOT NULL DEFAULT 'open',
        priority VARCHAR(10) NOT NULL DEFAULT 'normal',
        assigned_to INT NULL,
        sla_due_at DATETIME NULL,
        resolution TEXT NULL,
        created_at DATETIME NOT NULL,
        updated_at DATETIME NULL,
        resolved_at DATETIME NULL,
        KEY ix_tickets_status (status, sla_due_at),
        KEY ix_tickets_user (user_id)
    ) {TABLE_OPTS}""",
    f"""CREATE TABLE support_ticket_messages (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        ticket_id BIGINT NOT NULL,
        author_id INT NOT NULL,
        author_type VARCHAR(20) NOT NULL DEFAULT 'user',
        body TEXT NOT NULL,
        attachments JSON NULL,
        created_at DATETIME NOT NULL,
        KEY ix_tm_ticket (ticket_id)
    ) {TABLE_OPTS}""",
]


def up(conn):
    add_columns(conn, 'admin_users', USER_COLUMNS)
    add_index(conn, 'admin_users', 'ix_admin_users_account_status', 'account_status')
    add_index(conn, 'admin_users', 'ix_admin_users_phone_e164', 'phone_e164')
    create_tables(conn, TABLES)


def down(conn):
    drop_tables(conn, ['support_ticket_messages', 'support_tickets', 'background_checks',
                       'driver_documents', 'driver_applications', 'legal_acceptances',
                       'legal_documents', 'user_devices', 'phone_verifications'])
    drop_columns(conn, 'admin_users', [c.split()[0] for c in USER_COLUMNS])
